{
 "title": "adfundumtimer",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "scoreboard",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\r\n  ROW_NUMBER() OVER (ORDER BY s.drinktijd ASC) AS P,\r\n  d.naam       AS Deelnemer,\r\n  s.drinktijd  AS Drinktijd,\r\n  s.created_at AS DatumTijd\r\nFROM drinksessies s\r\nJOIN deelnemers d\r\n  ON d.id = s.deelnemer_id\r\nWHERE $__timeFilter(s.created_at)\r\nORDER BY s.drinktijd ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "laatse drinktijd",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\r\n  d.naam                AS Persoon,\r\n  ds.drinktijd          AS LaatsteDrinkTijd,\r\n  ds.created_at         AS Tijdstip\r\nFROM drinksessies ds\r\nJOIN deelnemers d\r\n  ON ds.deelnemer_id = d.id\r\nWHERE $__timeFilter(ds.created_at)\r\nORDER BY ds.created_at DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Top 3 Snelste Tijden Aller Tijden",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\r\n  d.naam        AS Deelnemer,\r\n  s.drinktijd   AS Drinktijd,\r\n  s.created_at  AS DatumTijd\r\nFROM drinksessies s\r\nJOIN deelnemers d ON d.id = s.deelnemer_id\r\nORDER BY s.drinktijd ASC\r\nLIMIT 3;\r\n"
    }
   ]
  },
  {
   "title": "Laatste drinktijd",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\r\n  drinktijd AS last_time\r\nFROM drinksessies\r\nWHERE $__timeFilter(created_at)\r\nORDER BY created_at DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Tijdenverdeling",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN drinktijd < 5 THEN '< 5 s'\r\n    WHEN drinktijd >= 5 AND drinktijd <= 10 THEN '5 – 10 s'\r\n    ELSE '> 10 s'\r\n  END AS category,\r\n  COUNT(*) AS aantal\r\nFROM drinksessies\r\nWHERE $__timeFilter(created_at)\r\nGROUP BY category;\r\n"
    }
   ]
  },
  {
   "title": "Aantal sessies",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "afstudeer_project",
     "rawSql": "SELECT\n  d.naam           AS Deelnemer,\n  COUNT(*)         AS AantalSessies\nFROM drinksessies ds\nJOIN deelnemers d\n  ON ds.deelnemer_id = d.id\nWHERE $__timeFilter(ds.created_at)\nGROUP BY d.naam\nORDER BY AantalSessies DESC;\n"
    }
   ]
  }
 ]
}